services:
  - type: web
    name: hollow-knight-bot
    env: python
    buildCommand: pip install -r requirements-prod.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_PATH
        value: /tmp/bot.sqlite3
      - key: LOG_LEVEL
        value: INFO
